export const caseTypes = {
  Civil: [
    { label: "Civil Suit", code: "CS" },
    { label: "Civil Appeal", code: "CA" },
    { label: "Civil Revision", code: "CR" },
    { label: "Civil Miscellaneous Application", code: "CMA" },
    { label: "Execution Petition", code: "EP" },
    { label: "Original Suit", code: "OS" },
    { label: "Regular Civil Appeal", code: "RCA" },
    { label: "Second Appeal", code: "SA" },
    { label: "Review Petition", code: "RP" },
    { label: "Transfer Petition", code: "TP" },
    { label: "Injunction Application", code: "IA" },
    { label: "Arbitration Petition", code: "ARB" },
    { label: "Company Petition", code: "CP" },
  ],
  Criminal: [
    { label: "Bail Application", code: "BA" },
    { label: "Anticipatory Bail", code: "ABA" },
    { label: "Criminal Appeal", code: "CRL.APL" },
    { label: "Criminal Revision", code: "CRL.REV" },
    { label: "Criminal Miscellaneous", code: "CRL.MISC" },
    { label: "Criminal Original", code: "CRL.O" },
    { label: "Sessions Case", code: "SC" },
    { label: "Warrant Case", code: "WC" },
    { label: "Summons Case", code: "SUM" },
    { label: "Final Report", code: "FR" },
    { label: "Charge Sheet Case", code: "CSH" },
  ],
  Family: [
    { label: "Divorce Petition", code: "DIV" },
    { label: "Maintenance Case", code: "MAINT" },
    { label: "Custody Petition", code: "CUST" },
    { label: "Domestic Violence Case", code: "DV" },
    { label: "Family Main Case", code: "FMC" },
    { label: "Family Miscellaneous Case", code: "FMISC" },
  ],
  Commercial: [
    { label: "Commercial Suit", code: "COM.SUIT" },
    { label: "Commercial Appeal", code: "COM.APL" },
  ],
  Consumer: [
    { label: "Consumer Complaint", code: "CC" },
    { label: "Consumer Appeal", code: "CCA" },
  ],
  Labour: [
    { label: "Labour Main Case", code: "LABOUR MAIN" },
    { label: "Labour Appeal", code: "LABOUR APL" },
    { label: "Labour Miscellaneous", code: "LABOUR MISC" },
  ],
  Tribunal: [
    { label: "DRC (Debt Recovery Case)", code: "DRC" },
    { label: "RERA Complaint", code: "RERA" },
    { label: "NCLT Petition", code: "NCLT" },
  ],
  Special: [
    { label: "Cheque Bounce (NI Act 138)", code: "NI138" },
    { label: "NDPS Case", code: "NDPS" },
    { label: "Motor Accident Claim (MACT)", code: "MACT" },
    { label: "Rent Case", code: "RENT" },
    { label: "Rent Appeal", code: "RENT APL" },
  ],
  Writ: [
    { label: "Writ Petition (Civil)", code: "WP(C)" },
    { label: "Writ Petition (Criminal)", code: "WP(CRL)" },
    { label: "Public Interest Litigation", code: "PIL" },
    { label: "Contempt Petition", code: "CONT" },
  ],
} as const;
